name: Release Docker images

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker-release:
    name: Release Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/enclosed:latest
            ghcr.io/${{ github.repository_owner }}/enclosed:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
